---
title: "Developing games half done and rush is bad"
date: 2022-08-25
---
title: Developing games half done and rush is bad
theme: minima
author: John Jones
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Video game companies are rushing out too many games to get ahead of trends instead of making polished games that will stand the test of time. 

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
